<template>
  <div>
    <div class='item-box' v-for='(item, index) in list[1].items'>
      <small>{{ index }}</small> <div v-html='hello(item)' style="display: inline; font-size: 18px;"></div>
<a href="#"></a>
    </div>
  </div>
</template>

<script>
export default {
  name: 'hello',
  data () {
    return {
      list: [
        {
          'category': 'Resources',
          'items': [
            'Official Guide',
            'API Reference',
            'GitHub Repo',
            'Release Notes',
            'Vue.js資料まとめ(for japanese) by @hashrock',
            'Vue.js Newsletter - Weekly dose of handpicked Vue.js news',
            'Vue.js Tips - Tips to become a better Vue.js developer',
            'Vue.js Wikipedia',
            'Vue.js Jobs - VueJobs - A Vue.js job portal to hire or get hired for all your Vue.js jobs.',
            'Twitter',
            'Gitter Chat Room',
            'Official Forum',
            'vue-requests - Request a Vue.js module you wish existed or get ideas for modules',
            'VueJS Brasil - Telegram Group [Portuguese]',
            'VueJS Iran - Telegram Channel & group (group link available in channel bio)',
            'vueslack - 1300+ registered users worldwide',
            'Full Stack Radio #30 (11-23-2015)',
            'JavaScript Jabber #187 (11-25-2015)',
            'Changelog #184 (11-27-2015)',
            'Software Engineering Daily (12-29-2015)',
            'Javascript Air 016 (03-30-2016)',
            'Codecasts #2 - Falando Sobre Vuejs e Web Components (2016-08-19) [pt-BR]',
            'Full Stack Radio #50 (09-21-2016)',
            '和 Vue.js 框架的作者聊聊前端框架开发背后的故事 [zh-CN]',
            'Vue.js TodoMVC',
            'CoffeeScript Version',
            'Vue.js HackerNews Clone',
            'Vue.js screencasts on Laracasts',
            'What\'s New in Vue.js 1.0 on Sitepoint',
            'Build an App with Vue.js: From Authentication to Calling an API on Auth0 blog',
            'Create a GitHub File Explorer Using Vue.js on Scotch.io',
            'Vue.js Tutorial on Vegibit',
            'Vue.js build set-up from scratch with webpack, vue-loader and hot reload',
            'Vuex basics: Tutorial and explanation',
            'Vuex introduction video - James Browne from London Vue.js Meetup #1',
            'Vue.js 中文系列视频教程 on Laravist',
            'Vue.js: The Basics on Coligo.io',
            'VueJs: Components on Coligo.io',
            'Dynamic Components in Vue.js on Coligo.io',
            'Develop a Reactive Invoice App using Vue.js on craigmckenna.com',
            'Understanding Filters in Vue.js on Coligo.io',
            'Hybrid App Example with Laravel and Vue.js in portuguese by @vedovelli',
            'Creating a Markdown Editor with VueJs and GitHub\'s API on Coligo.io',
            'Building a Real-Time Web Analytics Dashboard with NodeJs, Socket.io, and VueJs on Coligo.io',
            'Vue.js Introduction Turkish Languag on oguzhan.in',
            'Vue.js VideoTutoral Series in Spanish (3-8-2016) on YouTube by Juan Andrés Núñez',
            'Building a Bookmarking App with Electron, VueJs, and Firebase on Coligo.io',
            'Learn Vuex by Building a Notes App on Coligo.io',
            'Vue.js Screencast Series in Spanish on Styde.net',
            '讲解Vue.js 官网 中文-含代码、百度云、youtube on bhnddowinf',
            'Exploring Real Time Apps with VueJS, ES2015 and Webpack on Pusher',
            'Vue.js in Bahasa Indonesia on sekolahkoding.com',
            'Building a Mobile App with Cordova and Vue.js on Coligo.io',
            'Vue.js from Scratch Series in Russian on YouTube by .dev',
            'Створення сервісу для зберігання файлів з Flask, RethinkDB та Vue.js, ч. 1 Ukraine',
            'VueJS 2 French tutorial Français par Grafikart',
            'Jayway Vue.js 2 workshop. Build an e-commerce site with vue-router, vuex and vue-resource',
            'How to Create Great VueJS Applications Using Wijmo Controls',
            '**讲解Vue.js 2 官网 中文-含代码、百度云、youtube ** on bhnddowinf',
            'Vue.js Cheatsheet: Server-side Applications, Router, Vuex Store, GraphQL and more by @xpepermint',
            'Medium like Image Loading with Vue.js',
            'How to Use Vuex in a Laravel Spark Project on Metric Loop',
            'How To Set Up Modules in Vuex on Metric Loop',
            'Learn Vue 2: Step By Step on Laracasts',
            'Vue.js 中文教程',
            'Up and Running with the Vue.js 2.0 Framework on SitePoint',
            'How to make API Calls with Vuex on Metric Loop',
            'How to Use Vuex to Build a Feature on Metric Loop',
            'Vue.js 2.0 Fundamentals on YouTube by DevMarketer',
            'Vuex For The Clueless — The Missing Primer On Vue’s Application Data Store',
            'Real-time Grid Component Laravel, Vue.js, Vuex & Socket.io',
            'VueJS 2 - The Complete Guide (incl. Vuex) - Udemy Tutorial',
            'Develop Web Apps with Vue.js on egghead.io',
            'Vue.js 2 - Getting Started',
            'Vue.js 2 & Vuex (Basics)',
            'Türkçe VueJS Eğitim Videoları on YouTube by Fatih Acet',
            'Building a JSON Tree View Component in Vue.js from Scratch in Six Steps on digimondo devblog by Arvid Kahl',
            'Let\'s Vue! - OpenLecture 2017.01 in Russian on YouTube by Illya Klymov (@xanf)',
            'Bootstrapping your first Vue.js application using vue-cli by @afropolymath',
            'Bulid vue-hackernews-2.0 from Scratch by @ Detachment',
            'Role Based Authorization for your Vue.js and Nuxt.js Applications Using vue-kindergarten',
            'Complete Vue.js Application Tutorial - Creating a Simple Budgeting App with Vue by @matthiaswh',
            'Starter Application with JWT Auth + sample backend API in Laravel',
            'Node Webkit + Vue example by @brandonjpierce',
            'Vue Samples by @superlloyd',
            'HackerNews clone with vue.js + vue-router by @kazupon',
            'Electron + Vue example by @bradstewart',
            'Single page application example (Vue + Voie) by Boris Okunskiy',
            'Begin - Task Manager SPA written in Vue + Lumen by Raj Abishek',
            'Vue Mini Shop by BosNaufal',
            'Vue SoundCloud by mul14',
            'Feature Requests (Laravel + Vue Combo) by haydenbbickerton',
            'Vue Cookbook (Vue1.0 + express) by @yjj5855: A demo first screen rendering of a service',
            'Strong Together - A starter project to build single page Vue.js apps as stand-alone or for Laravel / Laravel Spark projects, based on Browserify and Semantic-ui) by WebSemantics',
            'vuetest: an ad admin web with user auth, bootstrap ui, uploader, WYSIWYG editor in iframe',
            'vue-shopping by andylei18',
            'Vue-cnodejs,060 by @shinygang',
            'vue-zhihu-daily by hilongjw',
            'jwt-example by @petervmeijgaard',
            'VueChess -Multiplayer online chess game by gustaYo',
            'Ngexplorer-vuejs-client -Vue client for Ngexplorer by gustaYo',
            'Vue 2048 (Vue + Webpack) by @pengfu: Popular 2048-Game implemented using Vue,Webpack,Sass,ES6',
            'Vue Simple PWA by BosNaufal',
            'Tour of Heroes (Vue 2.0): A Vue 2.0 port of the Angular 2.0 Tour of Heroes demo app. Highlights: ES6/7, render functions, JSX, revue (redux bindings for Vue), vue-router, Airbnb eslint, webpack. by @aweber1',
            'vue-table-pagination A table with pagination by echovic',
            'Feathers and Vue 2.0 Blog Admin Demo Demo for using Feathers with Vue 2.0. It includes authentication, vue-router, vue-infinite-loading and roles by delay',
            'vue-zhihudaily-2.0 Zhihudaily demo built with Vue 2.0, vue-router & vuex, with server-side rendering. by cs1707',
            'vue-demo-todolist a simply vue2.0 demo built with Vue 2.0, vue-cli. by fishenal',
            'vue-AdminLte by liujians',
            'Vue(2.0) + Node.js: A blog content manage system (CMS) by @ycwalker',
            'ngexplorer-quasar -Implementation of Ngexplorer with quasar framework by gustaYo',
            'zhihu-daily-vue a zhihu daily base on vue2.0 by moonou',
            'loopback-vue loopback+vue+vue-resource,ionic-app,vue page分页功能,authenticate 权限控制,accesstoken机制,credentials,CI,docker qxl1231',
            'vue-s3-dropzone A Vue.js drag-and-drop component uploads files to AWS S3 serverlessly',
            'easy-vue a easy example using the vue to implement easy web with vue 2.0, vuex 2.0, vue-router 2.0, vue-infinite-scroll 2.0, vue-progressbar 2.0 by TIGERB',
            'Vuex Events Messaging Demo by Metric Loop',
            'vue-memo a simple demo build with Vue.js(>2.x.), vue-router(>2.x.), vuex(>2.x.), vuex-router-sync@next(>3.x.) and Firebase(>3.6.x) by akifo',
            'Resume Vue JSON based Resume based on Vue 2.0 by ChangJoo Park',
            'App example with JWT Authentication developed with Phoenix Framework, Vue and Vue Router (demo) by @Angarsk8',
            'Sample CRUD app with router in Vue 2.0 by @shershen08',
            'ASP.NET Core Vue.js server-side rendering sample by @mgyongyosi',
            'vuefire-quickstart - Documented Firebase integration w/ webpack and eslint, by @sejr.',
            'hello-vue-django Vue.js and Django integration starter project with hot code reload',
            'Real Time Social News App developed with Phoenix, Vue, Vue Router and Vuex (demo) by @Angarsk8',
            'vue-calculator a simply calculator built with Vue 2.0, vue-cli(webpack-simple). by CaiYiLiang',
            'Wikipedia-viewer A simple wikipedia-viewer page built with vue2.x ,vue-router,vue-cli(webpack-simple) and ajax(jsonp). by CaiYiLiang',
            'vue2.x-douban A simple of douban movie build with vue2.x,vue-router and axios(豆瓣电影). by Superman',
            'vue-laravel-example Vue - Laravel - Example is a simple example to set Vue with Laravel. by Jiajian Chan',
            'vue-foundation A demo app integrating VueJS with Zurb Foundation, built using the webpack vue-cli template',
            'aspnetcore-Vue-starter A VueJS 2 starter template as part of an asp.net MVC dotnetcore project. This template includes the VueJS client app and a backend API controller.',
            'vue-reddit-app A Reddit SPA demo built with Vue 2.X , Vue Router 2 , Vuex and axios. Using Muse-UI and vue-cli webpack template by @yujiahaol68',
            'vue-music-qq A qq-music project is based on vue-cli. The pages are simple and smooth',
            'NavigationTab with Vue-Redux and Plain VueJSX Navigation Tab with both plain Vue JSX and Vue + Redux Binding',
            'Veggie Map An interactive demo using Vuejs + Vue router + Leaflet and Firebase',
            'vuejs-d3 examples how to use d3 for visualisations.',
            'The Majesty Of Vue.js by Alex Kyriakidis & Kostas Maniatis, Packt. (Nov 2016)',
            'Learning Vue.js 2 by Olga Filipova, Packt. (Dec 2016)'
          ]
        },
        {
          'category': 'Projects',
          'items': [
            'PageKit - Modular and lightweight CMS built with Symfony components and Vue.js.',
            'npmcharts.com - Compare npm packages and spot download trends.',
            'Koel - A personal music streaming server that works.',
            'RSS Reader - Simple RSS Reader made using atom electron and vue.js.',
            'Gokotta - A simple music player built by electron and vue.',
            'CoPilot - An admin portal based on AdminLTE with vue.js integration.',
            'Retrospectify - A simple tool for doing collaborative retrospectives in agile teams.',
            'jade-press - Cms based on mongodb, nodejs, koa, vue and more.',
            'astralapp - Organize Your GitHub Stars With Ease.',
            'EME - An Elegant Markdown Editor.',
            'Github-explorer - A spa which can help you check your github in a better way.',
            'Hotel - Start your dev servers from your browser and get local domains in seconds.',
            'Surfbird - A Twitter client written with modern web technologies.',
            'Approach0 - A math-aware search engine.',
            'Flox - Self Hosted Movie, Series and Anime Watch List.',
            'JavaScript Guessing Game - A game for identifying JavaScript tools and libraries.',
            'vue-ghpages-blog - A blog based on GitHub pages by Vue.js 2 + Webpack 2.',
            'Vuedo - Blog platform, built with Laravel and Vue.js.',
            'vue-music163 - A Vue.js project for music.',
            'Tomato5 - Real-time collaboration tool, it combines Pomodoro Technique with a team status share board.',
            'Peek-a-tab - Tabs Manager for Google Chrome.',
            'Web Learn - A service which provides simple access to thousands of video tutorials on web developing and programming.',
            'ExcelJSON - A tool to convert CSV, TSV to/from JSON.',
            'Materialize-blog - A material blog built with Laravel5.3 and Vue2.x.',
            'VueCompomnentGenerator - Generate vue single file component on browser.',
            'SDR News - News for web designers and developers aggregated from multiple sources (Reddit, Hacker News and Prominent Blogs).',
            'PJ Blog - Open source blog built with Laravel and Vue.js.',
            'Lulumi-browser - Lulumi-browser is a light weight browser coded with Vue.js 2 and Electron.',
            'vue-wordpress-pwa',
            'OpenAPI 3 viewer - Browse and test a REST API described with the OpenAPI 3.0 Specification',
            'Wijmo - A collection of UI controls with VueJS support.',
            'Collate Notes',
            'Laravel Spark',
            'Vice Video',
            'Formlets',
            'Laracasts',
            'esa.io',
            '稀土掘金',
            'Prague Airport',
            'Portfolio Site',
            'Grammarly - Mistake-free writing service.',
            'Laravist',
            'Atiiv - An app aimed for personal trainers and their clients.',
            'Statamic',
            'Embalses! - A tool to report water dam level using the U.S. Geological Survey database.',
            'TravelMap - A simple way for travellers to create a blog based on a Map.',
            'Proper Cloth Shirt Builder - Custom shirt builder.',
            'CheckIt',
            'Reddit News - A browser extension which show notifications and news from reddit.',
            'Powerpuff Yourself by Cartoon Networks',
            '小桃酱',
            'cloudradioo - Web app that plays randomly all top 50 songs from the soundcloud charts',
            'vNotes - Simple and beautiful notepad to Markdown with Vue.js and Local Storage API.',
            'Open Function Computers',
            'Dermail - A webmail client written in Vue.js for Dermail, a mail systemn written in node.js.',
            'octimine - A patent search engine.',
            'Draxed - A web based MySQL and PostgreSQL data browser and dashboard manager.',
            'Leapspotleap - A simple way to look up wikipedia articles near you. Or simply navigate to a place and find interesting wikipedia information. Responsive web app.',
            'X-SONGTAO - A Personal blog. FE and CMS are in same vue SPA.',
            'Cinemateka - Film & events schedule SPA made with Vue & Laravel 5. Russian.',
            'Jobinja - A Job Board and career platform operating in Iran.',
            '滚蛋吧！莆田系 - Show all Putian hostiptal information',
            'Jobi : Recruiting Platform',
            'The Spice House - Ecommerce website for high quality spices. Checkout, cart, the product detail page, and search are built using Vue. Checkout is a single page app written with Vue & Vuex.',
            'Livestorm - Webinar / Live events app.',
            'Metric Loop - A technology services and solutions website.',
            'Holden',
            'Global-Exam - Online Training for Language Proficiency Tests',
            'SlugSurvival - A webapp that helps student better plan their courses (hobby project, not in affiliation with UCSC).',
            'FreePoll.Online - A group decision making tool built using Vue.js, vue-sortable, Semantic UI and Zappa.',
            'GitRelease - Track github project\'s new release on mac menubar using vue.js with electron.',
            '12BAY.VN - Applications online flight bookings.',
            'PLAYCODE.IO - Playground for Rapid Frontend Experiments.',
            'Vue.js Calendar - A calendar app built with Vue.js, Vuex and server-side rendering.',
            'The Void Radio - Underground House Music Online Radio.',
            'Bitly Vue - Shorten URLs with VueJS & Bitly API.',
            'Storyblok - API Based/Decoupled CMS using VueJS for it\'s frontend.',
            'WizzAir',
            'Moving to HTTPS - Guide to moving different platform/hosting sites to HTTPS',
            'Booknshelf - Discover great books and bookshelves on different topics.',
            'Coypu - Text-editor-like weekly planner',
            'Top HN - A real time display of top news activity on Hacker News',
            'Euronews - Euronews is a multilingual news media service, headquartered in Lyon, France.',
            'Roozame روزامه� - Roozame is a persian smart news media service.',
            'Koumoul',
            'Jean-Pierre Morin | 1700 LAPOSTE',
            'Facebook NewsFeed',
            'YouTube AdBlitz 2016',
            'Omnisense Experience',
            'Louis Ansa Website (portfolio)',
            'Djeco.com',
            'Tolks.io',
            'Meet Graham',
            'NOIZE original',
            'Alibaba',
            'Baidu',
            'Sina Weibo',
            'Xiaomi',
            'Ele.me',
            'Optimizely',
            'Expedia',
            'UCWeb',
            'Line',
            'Nintendo',
            'Celtra',
            'Sainsbury\'s',
            'AREX',
            'DJI',
            'Octimine GmbH',
            'Hunliji',
            'GitLab',
            'Clemenger BBDO Melbourne',
            'ZenMate',
            'Codeship'
          ]
        },
        {
          'category': 'Components & Libraries',
          'items': [
            'vuetable-2 - Data table simplify.',
            'vue-tables-2 - Vue.js 2 grid components.',
            'vue-datasource - A vue.js server side component to create dynamic tables.',
            'ag-grid-vue - Vue adaptor for ag-Grid.',
            'vue-data-tables - Vue2.0 DataTables, based on element-ui.',
            'vue-notifications - Vue.js agnostic non-blocking notifications library.',
            'vue-easy-toast - A toast plugin for vue/vue2.',
            'vue-toasted - Responsive Touch Compatible Toast plugin for VueJS.',
            'vue-radial-progress - Radial progress bar component for Vue.js.',
            'vue-progressbar - A lightweight progress bar for vue.',
            'vue2-loading-bar - Simplest Youtube Like Loading Bar Component For Vue 2.',
            'vue-top-progress - Yet another top progress loading bar component for Vue.js.',
            'vue-nprogress - Progress bars is based on nprogress for Vue.',
            'v-tooltip - Easy tooltips with Vue 2.x.',
            'vue-popper-component - Popper.js directive for Vue.js.',
            'vuedals - A VueJS (2.x) Plugin for multiple modals windows with a single component instance.',
            'sweet-modal-vue - The sweetest library to happen to modals. Now available for Vue.js.',
            'vue-parallax - Scrolls a image slower than the window to create a neat optical effect.',
            'vue-parallaxy - Vue.js component for parallax image scroll effects.',
            'vue-icons - Webpack based - load only what you need - svg inline icons.',
            'vue-awesome - Font Awesome component for Vue.js, using inline SVG.',
            'vue-side-nav - Side-nav.',
            'vue-easy-slider - Slider Component of Vue.js.',
            'vue-l-carousel - A responsive carousel(namely slider or swiper) component for Vue.js v2.x+.',
            'vue-awesome-swiper - Swiper(slide) component for Vue.js(1.x ~ 2.x).',
            'vue-lory - Vue Slider Component based on lory.',
            'vue-slick - Vue component for Slick-carousel.',
            'vue-flickity - A Vue Component for Flickity.js.',
            'vue-carousel-3d - Vue Carousel 3D - Beautiful, flexible and touch supported 3D Carousel for Vue.js.',
            'vue-carousel - A flexible, responsive, touch-friendly carousel for Vue.js.',
            'vue-morris - VueJS component wrapping Morris.js.',
            'vue-charts - Google Charts plugin for Vue.js.',
            'vue-chartjs - Vue.js wrapper for Chart.js.',
            'hchs-vue-charts - Based on Vue2.0 wrapper for ChartJs.',
            'vue-echarts - ECharts component for Vue.js.',
            'vuetrend - Simple, elegant spark lines for Vue.js.',
            'vue-highcharts - Highcharts component for Vue.',
            'vue-echarts-v3 - Vue.js(v2.x+) component wrap for ECharts.js(v3.x+).',
            'vue-timeago - A tiny timeago component for Vue.',
            'vue-moment-jalaali - Jalaali Moment.js filters for your Vue.js project.',
            'vue-fullcalendar - Vue calendar fullCalendar. No jQuery required. Schedule events management.',
            'vue-event-calendar - A simple events calendar for Vue2, no dependencies except Vue2.',
            'vue2-google-maps - Google maps component for vue with 2-way data binding.',
            'vue2-leaflet - Vue 2 components for Leaflet maps.',
            'vue-aplayer - A Vue 2.x component of easy-to-config music players with controls.',
            'vue-infinite-loading - An infinite scroll plugin for Vue.js 1.0 & Vue.js 2.0.',
            'vue-mugen-scroll - Infinite scroll component for Vue.js 2.',
            'vue-infinite-scroll - An infinite scroll directive for vue.js.',
            'vue-markdown - A Powerful and Highspeed Markdown Parser for Vue.',
            'vue-json-tree-view - A JSON Tree View Component for Vue.js.',
            'vue-social-sharing - A Vue.js component for sharing links to social networks, work with Vue.js 1.X or 2.X.',
            'vue-qriously - A Vue.js 2 component to draw QR codes on an HTML Canvas using qrious.',
            'vue-qart - The directive of vue 2.x for qart.js.',
            'vue-avatar - An avatar component for vue.js.',
            'vue-touch-ripple - Touch ripple component for Vue.js(1.x ~ 2.x).',
            'vue-typer - Vue component that simulates a user typing, selecting, and erasing text.',
            'vue-keyboard - Vue 2 virtual keyboard component.',
            'vue-twentytwenty - Image comparison component, works with Vue.js 2.x',
            'vue-cookie-law - Cookie info plugin for Vue.js 2.x',
            'vue-datepicker - Calendar and datepicker component with material design for Vue.js.',
            'vue2-timepicker - A dropdown time picker (hour|minute|second) for Vue 2.x, with flexible time format support.',
            'vuejs-datepicker - A simple Vue.js datepicker component. Supports disabling of dates, inline mode, translations.',
            'vue-flatpickr - Flatpickr for VueJS.',
            'vue-select - A native Vue.js component that provides similar functionality to Select2 without the overhead of jQuery.',
            'vue-multiselect - Universal select/multiselect/tagging component for Vue.js.',
            'vue-slider-component - Slider for vue1.x and vue2.x.',
            'vuedraggable - Vue component allowing drag-and-drop sorting in sync with View-Model. Based on Sortable.js.',
            'vue-dragula - Drag and drop so simple it hurts.',
            'awe-dnd - A sortable list directive with Vue.',
            'vue-instant - Vue instant allows you to easily create custom search controls with auto suggestions for your vue 2 applications.',
            'vue-tagsinput - A tags input component based on Vue.js.',
            'vue-input-tag - Vue.js 2.0 Input Tag Component.',
            'v-distpicker A flexible, highly available district picker for picking provinces, cities and districts of China for Vue.js 2.x.',
            'vue-color - Vue Color Pickers for Sketch, Photoshop, Chrome & more.',
            'vue-switches - An on/off switch component for Vue.js with theme support.',
            'vue-masked-input - Masked input component for Vue.js.',
            'vue-text-mask - Input mask for React, Angular, Ember, Vue, & plain JavaScript.',
            'vue-ip-input - An ip input implemented by vuejs.',
            'vue-numeric - Input field component to display currency value based on Vue.',
            'vue-quill-editor - Quill editor component for Vue2.',
            'vue-mobiledoc-editor - A mobiledoc editor component toolkit for Vuejs.',
            'vue2-medium-editor - A MediumEditor component for Vue 2.',
            'vue-froala - VueJS wrapper for Froala Editor.',
            'vue-core-image-upload - A vue plugin for image to crop and upload.',
            'vue-clip - Simple and hackable file uploader for VueJs. Supports Vue >= 2.1.',
            'vue-simple-upload - Simple File upload component for Vue.js.',
            'vue-context-menu - A context menu component for vue js.',
            'vue-gmaps - Search places and address using Google Maps API.',
            'vuep - A component for rendering Vue components with live editor and preview.',
            'vue-places - Places component is based on places.js for Vue 2.x. Turn any input into an address autocomplete.',
            'vue-password-strength-meter - Password strength meter based on zxcvbn in vue.js.',
            'vue-float-label - Float label pattern for Vue.js.',
            'vue-longpress - A VueJS (2.x) button component that requires you to keep pressing to confirm a given action.',
            'vue-embed - Embed component is based on embed.js for Vue 2.x, a component that embeds emojis, media, maps, tweets, gists, code, services and markdown.'
          ]
        },
        {
          'category': 'UI Layout',
          'items': [
            'vue-waterfall - A waterfall layout component for Vue.js.',
            'vueisotope - Vue component for isotope filter & sort magical layouts.',
            'vue-grid-layout - A draggable and resizable grid layout, for Vue.js.',
            'vue-drag-zone - Drag Zone component for Vue.js(2.x).',
            'vue-masonry - Vue.js directive for masonry blocks layouting.',
            'vue-fraction-grid - Flexbox based responsive fraction grid system for Vue.js.',
            'vue-virtual-scroll-list - A vue (2.x) component support big data by using virtual scroll list.'
          ]
        },
        {
          'category': 'Frameworks',
          'items': [
            'quasar-framework - Quasar Framework.',
            'vue-material - Material design for Vue.js.',
            'vuetify - Material Component Framework for Vue.js 2.',
            'framework7-vue - Full featured HTML framework for building iOS & Android apps.',
            'vux - [Chinese] Vue UI Components based on WeUI.',
            'vue-onsenui - Mobile app development framework and SDK using HTML5 and JavaScript. Create beautiful and performant cross-platform mobile apps. Based on Web Components, and provides bindings for Angular 1, 2, React and Vue.js.',
            'vue-mdl - Reusable Material Design Lite components for Vue.js.',
            'keen-ui - A lightweight collection of essential UI components written with Vue and inspired by Material Design.',
            'vue-admin - Vue Admin Panel Framework, Powered by Vue 2.0 and Bulma 0.3.',
            'vuikit - UIkit with all the power of Vue.',
            'element-ui - A Vue.js 2.0 UI Toolkit for Web.',
            'bootstrap-vue - Bootstrap 4 Components for Vue.js 2.',
            'uiv Bootstrap3 components implemented by Vue2.',
            'mint-ui - Mobile UI elements for Vue.js.',
            'nuxt - Framework for server-rendered Vue.js applications.',
            'app-framework - IOS and Android Apps with HTML & JavaScript - develop, build and deploy - free and open source.'
          ]
        },
        {
          'category': 'UI Utilities',
          'items': [
            'vue-shortkey - Vue-ShortKey - plugin for Vue.js.',
            'vue-throttle-event - Throttle events based on requestAnimationFrame.',
            'vue-waypoint - Waypoint component for Vue, this is the easiest way to trigger a function when you scroll.',
            'vue-clickaway - Reusable clickaway directive for reusable Vue.js components.',
            'vue-scrollfire - Fires an event on a specific scroll position.',
            'vue-resize-directive - Vue directive to detect resize events with deboucing and throttling capacity.',
            'vue-viewports - Define your custom viewports and use them in your components.',
            'vue-responsive: Vue.js(2.x) directive to hide/show HTML-elements with the Bootstrap 4, 3 or self defined breakpoints.',
            'vue-formly - JavaScript powered forms for Vue.js.',
            'vue-focus - A reusable focus directive for reusable Vue.js components.',
            'vue-form-generator - A schema-based form generator component for Vue.js.',
            'vue-validator - Validator component for Vue.js.',
            'vee-validate - Simple Vue.js input validation plugin.',
            'vue-rawmodel - RawModel.js plugin for Vue.js v2. Form validation has never been easier.',
            'vuelidate - Simple, lightweight model-based validation for Vue.js.',
            'simple-vue-validator - A simple yet flexible validator library for vue.js.',
            'vue-vform - Vue.js 2 form component that integrates jQuery Validation and Axios.',
            'vue-form - Comprehensive form validation for Vue.js.',
            'vue-chat-scroll - Automatic scroll-to-bottom directive for Vue.js 2.0.',
            'vue-scrollto - Adds a directive that listens for click events and scrolls to elements.',
            'vue-router - The official router for Vue.js.',
            'vue-lazyload - A Vue.js plugin for lazyload your Image or Component in your application.',
            'vue-lazy-background-images - Lazy load background images for Vue 2.',
            'vue-progressive-image - Vue progressive image loading plugin.',
            'vue-l-lazyload - A lazyload plugin for Vue.js v2.x+.',
            'vue-paginate - A simple vue.js plugin to paginate data.',
            'vue-pagination-2 - Vue.js 2 pagination component.',
            'vuejs-uib-pagination - Best and complete pagination plugin for Vue.js. Inspired in Angular Bootstrap Pagination.',
            'vuejs-paginate - A Vue.js(v2.x+) component for creating pagination.',
            'vue2-animate - A Vue.js 2.0 port of Animate.css. For use with Vue\'s built-in transitions.',
            'vue-head - Manage the meta information of the head tag, a simple and easy way.',
            'vue-meta - Manage page meta info in Vue 2.0 components. SSR + Streaming supported.',
            'Move a DOM node to a target DOM node',
            'vue-dom-portal - An escape hatch for DOM Elements in Vue.js components.',
            'vue2-filters - A collection of standard filters Vue 1.* adapted for use in Vue 2.*.',
            'vue-svgicon - A tool to create svg icon components. (vue 2.x).',
            'vue-resource-progressbar-interceptor - Interceptor that ties a progressbar to all requests, that it is clear that something is loading.',
            'vue-images-loaded - Vue.js 2.0 directive to detect images loading.',
            'vue-visible - A v-visible directive for VueJS (2.x), like v-show but for visibility.'
          ]
        },
        {
          'category': 'Utilities',
          'items': [
            'vue-typed - Sets of ECMAScript / Typescript decorators that helps you write Vue component easily.',
            'vue-typescript - Typescript decorators to make vue feel more typescripty.',
            'vue-property-decorator - Vue.js and Property Decorator.',
            'vue-typescript-component - Decorators to use TypeScript classes as Vue.js 2.0 components.',
            'vue-typescript-import-dts - TypeScript declaration file that allows using \'import\' with .vue files.',
            'vue-ts-loader - Type-check your script in your vue-loader.',
            'vue-resource - The HTTP client for Vue.js.',
            'vue-async-computed - Async computed properties for Vue.js.',
            'vue-jsonp - A tiny library for handling JSONP request.',
            'v-model - V-Model is a model plugin for Vue.js, like ng-resource.',
            'vue-resource-mock - A helper to mock your http response, based on vue-resource\'s inteceptor.',
            'vue-i18n - Internationalization plugin for Vue.js.',
            'vue-translate-plugin - VueJS plugin for translations.',
            'vuex-i18n - Localization plugin for vue.js 2.0 using vuex as store.',
            'vue-gettext - Translate your Vue.js applications with gettext.',
            'vue-events - Simple event handling for Vue.js.',
            'vue-event-handler - Event handling plugin for VueJS.',
            'vue-localstorage - Vue.js localStorage plugin with types support.',
            'vue-ls - Vue plugin for work with LocalStorage from Vue context.',
            'vuex - Centralized State Management for Vue.js.',
            'vue-sync - Synchronize Vue State with the Browser URL, Server Backend, and other endpoints.',
            'revue - Redux binding for Vue.',
            'vuedeux - Binding Solutions for Vue & Redux.',
            'vue-kindergarten',
            'vuex-persistedstate - Persist Vuex state with localStorage.',
            'vuex-plugin-jsdata - A plugin for syncing Vuex store with js-data.',
            'vuex-local - Local state management within Vuex.',
            'vuex-action - Utilities for vuex to easily create and manage actions.',
            'vuex-rest-api - A Helper utility to simplify the usage of REST APIs with Vuex. Based on axios.',
            'vuex-cache - A Vuex plugin utility to cache action those will make remote request.',
            'vuex-basement - Vuex state persistance and synchronization between tabs/windows.',
            'vuex-shared-mutations - Share vuex mutations between tabs/windows.',
            'vue-types - Vue Prop Types definitions.',
            'vue-factory - A simple factory/provider extension for Vue.js, like services in Angular.',
            'eslint-plugin-vue - Eslint plugin for vue.js projects.',
            'vue-decorators - Decorators for VueJS (beta).',
            'vue-bem-cn - Simple BEM class name generator for Vue.JS.',
            'vue-script2 - Standardized, designer-friendly script tag behavior for your Single Page App.',
            'vue-loader - Webpack loader for Vue.js components.',
            'vueify - Browserify transform for single-file Vue components.',
            'vue-compiler - A simple cli wrapper around the vue-component-compiler.',
            'vue-brunch - Adds support to Brunch for pre-compiling single file Vue components.',
            'vbuild - Fast prototype and distribute modern web apps like a pro.',
            'http-vue-loader - Load .vue files directly from your html/js without node.js environment nor build step.',
            'vue-navigation - A page navigation library, record routes and cache pages, like native app navigation. 一个页面导航库，记录路由并缓存页面，像原生APP导航一样。',
            'vue-container - A simple dependency injection library for Vue 2.',
            'vue-super - A simple plugin to call methods on parent components.'
          ]
        },
        {
          'category': 'Integrations',
          'items': [
            'vue-disqus - Vue component to integrate Disqus comments in your application, with support for SPA.',
            'vue-youtube-embed - Vue.js and YouTube.',
            'vue-add-to-calendar - A Vue.js component that provides \'Add to Calendar\' functionality, works with Vue 2.X.',
            'Vue + Meteor - Vue first-class integration in Meteor.',
            'vue-apollo - Apollo/GraphQL integration for VueJS.',
            'av-ts - A modern, type-safe, idiomatic Vue binding library.',
            'Neutronium - Build .NET desktop applications using HTML, CSS and javascript.',
            'vue-threejs - Vue bindings for Three.js.',
            'vue-typescript-jest - Jest preprocessor.js for Vue.js components (supporting html, pug, and babel) and TypeScript.',
            'vue-jest-utils - Utilities for testing Vue.js components using Jest.',
            'vue-custom-element - Vue Custom Element - Custom Elements for Vue.js.',
            'vue-socket.io - Socket.io implemantation for vuejs.',
            'vue-cordova - Vue.js plugin for Cordova.',
            'vue-websocket - Simple websocket (socket.io) plugin for Vue.js.',
            'vue-wamp - AutobahnJS wrapper library fo Vue.js.',
            'express-vue - Vue rendering engine for Express.js. Use .Vue files as templates using res.render().',
            'vue-ua - Google Universal Analytics support in Vue.js.',
            'vue-analytics - Vue plugin for Google Analytics.'
          ]
        },
        {
          'category': 'Dev Tools',
          'items': [
            'vue-dev-server - A small development server for building vue components.',
            'Vue.js devtools - Chrome devtools extension for debugging Vue.js applications.',
            'DejaVue - Visualization and debugging tool built for Vue.js.',
            'vue-markdown-loader - Convert Markdown file to Vue Component.',
            'vue-play - A minimalistic framework for demonstrating your Vue components.',
            'vue-styleguide-generator - React inspired style guide generator for Vue.js.',
            'avoriaz - A Vue.js testing utility library.',
            'vue-container - A simple dependency injection library for Vue 2.',
            'vuegister - Vuegister (an acronym for vue-register) is a require hook for loading of the Vue.js single-file components (or .vue files).',
            'vue-node - Load vue components in node.',
            'language-vue@atom.io - Vue component file syntax for Atom.',
            'language-vue-component@atom.io - Adds syntax highlighting to Vue Component files in Atom.',
            'vue-autocomplete@atom.io - Vue.js 1.0+ autocomplete for Atom.',
            'vue-snippets@atom.io - Atom snippets for Vue component files.',
            'vue-autocompile@atom.io - Auto compile vue file on save.',
            'Vue Syntax Highlight - Sublime Text syntax highlighting for single-file Vue components.',
            'Vim Vue - Syntax Highligth for Vue.js components.',
            'Vetur - Vue tooling for VSCode.',
            'VuePack - Contains HTML Intellisense and code snippets for the Vue.js JavaScript library.',
            'Brackets Vue - Brackets extension for Vue.js.',
            'Vue.js Plugin - Vue.js features for the Intellij Platform (WebStorm, RubyMine, Intellij, etc).',
            'Vue.js support for WebStorm, IntelliJ IDEA, PhpStorm, PyCharm & RubyMine – official Vue.js support by JetBrains',
            'Vue Mode - Emacs major mode for vue.js.',
            'Kate Syntax Files - Syntax files (modified or original) for katepart (kate, kwrite, kdevelop).'
          ]
        },
        {
          'category': 'Scaffold',
          'items': [
            'vue-cli - Simple CLI for scaffolding Vue.js projects.',
            'Vue Plugin Boilerplate - Boilerplate for Vue.js plugin.',
            'Bourgeon - Bourgeon is an opinionated-featured VueJS 2.0 setup for Webpack.',
            'VuePack - A modern starter which uses Vue 2, Vuex, Vue-router and Webpack 2 (and even Electron).',
            'Vue Settler - An opinionated Vue 2.0 SPA Starter.',
            'vue-build - Ultra Simple, Development, Testing and Production Build Cli.',
            'Vue Element Starter - Robust Vue 2 starter with Element-UI.',
            'vue-multiple-pages - A modern Vue.js multiple pages starter which uses Vue 2, Webpack2, and Element-UI',
            'Render Vue application to HTML on the server and to the DOM in the browser',
            'SPA Starter Kit - A highly opinionated starter kit for building Single Page Applications with Laravel and Vue.js.',
            'SSR Boilerplate - Vue.js Server Side Rendering Boilerplate without Polluting Vuex.',
            'Vuetober - Single page apps with Laravel, Vue.js, and October CMS.',
            'Electron Vue - An Electron & Vue.js quick start boilerplate with vue-cli scaffolding, common Vue plugins, electron-packager/electron-builder, unit/e2e testing, vue-devtools, and webpack.',
            'VuePack - A modern starter which uses Vue 2, Vuex, Vue-router and Webpack 2 (and even Electron).',
            'vue-generator - A CLI generator for Vue components, views and store modules.'
          ]
        }

      ]
    }
  },
  // computed: {
  //   hello: function (string) {
  //     var newString = string
  //
  //     return newString
  //   }
  // },
  methods: {
    hello: function (string) {
      var newString = string.split('-')

      if (newString[1] == null) {
        newString[1] = ''
      }

      return '<strong>' + newString[0] + '</strong> (mail.yahoo.com) <br><small>' + newString[1] + '<small>'
    }
  }
}
</script>

<!-- Add 'scoped' attribute to limit CSS to this component only -->
<style scoped>
.hello {
    margin-top: 0px;
    margin-bottom: 16px;
}

.item-box {
  color: #FFF;
  font-weight: 500;
  font-family: 'Open Sans';
  border-radius: 10px;
  background-color: rgba(255,255,255,.2);
  padding: 14px;
  margin-bottom: 6px;
}

.item-box:hover {
  background-color: rgba(255,255,255,.4);
}

item-box a:active {
    color: blue;
}

a {
  color: #7B1C99;
  font-weight: 500;
}

small {
  color: #FFF;
  font-weight: 500;
  font-size: 12px;
}

strong {
  font-weight: 700;
}
</style>
